<template>
  <c311-app-shell mode="staff" :brand="t('staff.brand', 'City 311 staff')" :title="isDetailView ? t('staff.detailTitle', 'Request detail') : t('staff.title', 'Requests')" :status-message="statusMessage">
    <template #nav>
      <div class="d-flex flex-wrap align-items-center gap-2">
        <c311-main-nav :items="navItems" :label="t('navigation.staff', 'Staff navigation')" />
        <c311-help-drawer help-key="staff.request.triage" :label="t('help.label', 'Help')" :title="t('help.title', 'Help')" :close-label="t('action.close', 'Close')" :content="t('help.staff.request.triage', 'Review and classify a request.')" />
        <c311-language-selector :actor-id="actorID" />
      </div>
    </template>

    <div v-if="!isDetailView" class="mb-3" data-c311-staff-filters>
      <form class="form-row" @submit.prevent="applyFilters">
        <div class="form-group col-md-2"><label for="c311-filter-status">{{ t('field.status', 'Status') }}</label><select id="c311-filter-status" v-model="filters.status" class="form-control"><option value="">{{ t('filter.all', 'All') }}</option><option v-for="status in statuses" :key="status" :value="status">{{ status }}</option></select></div>
        <div class="form-group col-md-2"><label for="c311-filter-service-type">{{ t('field.serviceType', 'Service type') }}</label><select id="c311-filter-service-type" v-model="filters.service_type" class="form-control"><option value="">{{ t('filter.all', 'All') }}</option><option v-for="type in serviceTypes" :key="type" :value="type">{{ type }}</option></select></div>
        <div class="form-group col-md-2"><label for="c311-filter-department">{{ t('field.department', 'Department') }}</label><select id="c311-filter-department" v-model="filters.department" class="form-control"><option value="">{{ t('filter.all', 'All') }}</option><option v-for="department in departments" :key="department" :value="department">{{ department }}</option></select></div>
        <div class="form-group col-md-2"><label for="c311-filter-district">{{ t('field.district', 'District') }}</label><select id="c311-filter-district" v-model="filters.district" class="form-control"><option value="">{{ t('filter.all', 'All') }}</option><option v-for="district in districts" :key="district" :value="district">{{ district }}</option></select></div>
        <div class="form-group col-md-2"><label for="c311-filter-origin">{{ t('field.origin', 'Origin') }}</label><select id="c311-filter-origin" v-model="filters.origin_class" class="form-control"><option value="">{{ t('filter.all', 'All') }}</option><option value="EXTERNAL">EXTERNAL</option><option value="INTERNAL">INTERNAL</option></select></div>
        <div class="form-group col-md-2"><label for="c311-filter-source">{{ t('field.source', 'Source channel') }}</label><select id="c311-filter-source" v-model="filters.source_channel" class="form-control"><option value="">{{ t('filter.all', 'All') }}</option><option value="PORTAL_ANONYMOUS">PORTAL_ANONYMOUS</option><option value="PORTAL_AUTHENTICATED">PORTAL_AUTHENTICATED</option><option value="STAFF_IN_PERSON">STAFF_IN_PERSON</option><option value="API">API</option></select></div>
        <div class="form-group col-md-2"><label for="c311-filter-assignee">{{ t('field.assignee', 'Assignee') }}</label><input id="c311-filter-assignee" v-model="filters.assignee" class="form-control"></div>
        <div class="form-group col-md-2"><label for="c311-filter-collaborator">{{ t('field.collaborator', 'Collaborator') }}</label><input id="c311-filter-collaborator" v-model="filters.collaborator" class="form-control"></div>
        <div class="form-group col-md-2"><label for="c311-filter-category">{{ t('field.category', 'Category') }}</label><input id="c311-filter-category" v-model="filters.category" class="form-control"></div>
        <div class="form-group col-md-2"><label for="c311-filter-created-from">{{ t('field.createdFrom', 'Created from') }}</label><input id="c311-filter-created-from" v-model="filters.created_from" type="datetime-local" class="form-control"></div>
        <div class="form-group col-md-2"><label for="c311-filter-created-to">{{ t('field.createdTo', 'Created to') }}</label><input id="c311-filter-created-to" v-model="filters.created_to" type="datetime-local" class="form-control"></div>
        <div class="form-group col-md-2"><label for="c311-filter-duplicate">{{ t('field.duplicateGroup', 'Duplicate group') }}</label><input id="c311-filter-duplicate" v-model="filters.duplicate_group" class="form-control"></div>
        <div class="form-group col-md-2"><label for="c311-filter-sort">{{ t('field.sort', 'Sort') }}</label><input id="c311-filter-sort" v-model="sort" class="form-control" :placeholder="t('field.sortPlaceholder', '-updated_at')"></div>
        <div class="form-group col-md-2"><label for="c311-filter-page-size">{{ t('field.pageSize', 'Page size') }}</label><input id="c311-filter-page-size" v-model.number="pageSize" type="number" min="1" max="100" class="form-control"></div>
        <div class="form-group col-md-2 d-flex align-items-end"><button class="btn btn-primary" type="submit" data-c311-action="apply-staff-filters">{{ t('action.applyFilters', 'Apply filters') }}</button></div>
      </form>
    </div>

    <button v-if="isDetailView" type="button" class="btn btn-link px-0 mb-3" data-c311-action="back-to-staff-queue" @click="backToQueue">{{ t('action.backToQueue', 'Back to queue') }}</button>

    <c311-data-state :state="state" :error="dataError" @retry="retryCurrentView">
      <template #populated>
        <section v-if="!isDetailView" aria-labelledby="c311-staff-heading">
          <h2 id="c311-staff-heading" tabindex="-1" class="h2">{{ t('staff.title', 'Requests') }}</h2>
          <p class="sr-only" aria-live="polite">{{ statusMessage }}</p>
          <c311-responsive-data :items="items" :columns="translatedColumns" row-key="request_id" :label="t('staff.queue', 'Staff request queue')" selectable selection-enabled :selected-keys="selectedRequestIds" :select-label="t('action.selectRequest', 'Select request')" :select-all-label="t('action.selectAllRequests', 'Select all requests')" :action-label="t('action.viewRequest', 'View request')" @select="selectRequest" @selection-change="selectedRequestIds = $event" />
          <section v-if="can('staff_request_bulk')" class="border rounded p-3 mt-3" data-c311-bulk-toolbar aria-labelledby="c311-bulk-heading">
            <h3 id="c311-bulk-heading" class="h5">{{ t('staff.bulkTitle', 'Bulk actions') }}</h3>
            <p class="small mb-2">{{ selectedItems.length }} {{ t('staff.selected', 'selected') }}</p>
            <form class="form-row" data-c311-form="bulk" @submit.prevent="openBulkConfirmation">
              <div class="form-group col-md-2"><label for="c311-bulk-action">{{ t('field.action', 'Action') }}</label><select id="c311-bulk-action" v-model="bulkForm.action" class="form-control"><option value="UPDATE">UPDATE</option><option value="CLOSE">CLOSE</option></select></div>
              <div class="form-group col-md-2"><label for="c311-bulk-assignee">{{ t('field.assignee', 'Assignee') }}</label><input id="c311-bulk-assignee" v-model.trim="bulkForm.primary_assignee_id" class="form-control"></div>
              <div class="form-group col-md-2"><label for="c311-bulk-status">{{ t('field.status', 'Status') }}</label><select id="c311-bulk-status" v-model="bulkForm.status" class="form-control" :disabled="bulkForm.action === 'CLOSE'"><option value="">{{ t('filter.none', 'No change') }}</option><option v-for="status in statuses" :key="status" :value="status">{{ status }}</option></select></div>
              <div class="form-group col-md-2"><label for="c311-bulk-priority">{{ t('field.priority', 'Priority') }}</label><input id="c311-bulk-priority" v-model.trim="bulkForm.priority" class="form-control"></div>
              <div class="form-group col-md-2"><label for="c311-bulk-note">{{ t('field.note', 'Staff note') }}</label><input id="c311-bulk-note" v-model.trim="bulkForm.staff_note" class="form-control"></div>
              <div class="form-group col-md-2 d-flex align-items-end"><button type="submit" class="btn btn-primary" data-c311-action="bulk-open-confirm" :disabled="!selectedItems.length || bulkBusy">{{ t('action.bulkReview', 'Review changes') }}</button></div>
            </form>
            <div v-if="bulkConfirmOpen" class="mt-2 p-2 border" role="dialog" aria-modal="true" tabindex="-1" data-c311-bulk-confirmation>
              <p>{{ t('staff.bulkConfirm', 'Apply this change to the selected requests?') }}</p>
              <dl class="row mb-2" data-c311-bulk-summary><dt class="col-5">{{ t('staff.selectedCount', 'Selected requests') }}</dt><dd class="col-7" data-c311-bulk-count>{{ selectedItems.length }}</dd><dt class="col-5">{{ t('field.action', 'Action') }}</dt><dd class="col-7">{{ bulkForm.action }}</dd><dt class="col-5">{{ t('staff.expectedChanges', 'Expected changes') }}</dt><dd class="col-7" data-c311-bulk-changes>{{ bulkChangeSummary }}</dd></dl>
              <button type="button" class="btn btn-primary btn-sm mr-2" data-c311-action="bulk-confirm" @click="submitBulk">{{ t('action.confirm', 'Confirm') }}</button><button type="button" class="btn btn-link btn-sm" data-c311-action="bulk-cancel" @click="bulkConfirmOpen = false">{{ t('action.cancel', 'Cancel') }}</button>
            </div>
            <p v-if="bulkMessage" class="text-info" role="status" aria-live="polite" data-c311-bulk-message>{{ bulkMessage }}</p>
            <div v-if="bulkError" class="text-danger" role="alert" data-c311-bulk-error>
              <p>{{ bulkError.message || bulkError }}</p><p v-if="bulkError.failingRequestID || bulkError.failing_request_id" data-c311-bulk-failing-request>{{ t('staff.failingRequest', 'Failing request') }}: {{ bulkError.failingRequestID || bulkError.failing_request_id }}</p><p v-if="bulkError.currentVersion || bulkError.current_version" data-c311-bulk-current-version>{{ t('staff.serverVersion', 'Server version') }}: {{ bulkError.currentVersion || bulkError.current_version }}</p>
              <div v-if="bulkError.status === 409"><button type="button" class="btn btn-link btn-sm pl-0 mr-2" data-c311-action="reload-bulk-version" @click="reloadBulkConflict">{{ t('action.reloadVersion', 'Reload current version') }}</button><button v-if="bulkConflictReloaded" type="button" class="btn btn-link btn-sm" data-c311-action="reapply-bulk" @click="reapplyBulk">{{ t('action.reapply', 'Reapply my operation') }}</button></div>
            </div>
          </section>
          <div class="d-flex justify-content-between align-items-center mt-3" data-c311-pagination>
            <button type="button" class="btn btn-outline-secondary" :disabled="!pageTokenHistory.length" data-c311-action="previous-page" @click="previousPage">{{ t('action.previous', 'Previous') }}</button>
            <span>{{ page.total_count }} {{ t('staff.results', 'results') }}</span>
            <button type="button" class="btn btn-outline-secondary" :disabled="!page.next_page_token" data-c311-action="next-page" @click="nextPage">{{ t('action.next', 'Next') }}</button>
          </div>
        </section>

        <section v-else-if="detail" aria-labelledby="c311-staff-detail-heading" data-c311-request-detail data-c311-staff-request-detail>
          <h2 id="c311-staff-detail-heading" tabindex="-1" class="h2">{{ detail.request.request_number || detail.request.request_id }}</h2>
          <div class="row">
            <div class="col-lg-8">
              <dl class="row">
                <dt class="col-sm-4">{{ t('field.requestNumber', 'Request number') }}</dt><dd class="col-sm-8">{{ detail.request.request_number || detail.request.request_id }}</dd>
                <dt class="col-sm-4">{{ t('field.summary', 'Summary') }}</dt><dd class="col-sm-8">{{ detail.request.summary }}</dd>
                <dt class="col-sm-4">{{ t('field.status', 'Status') }}</dt><dd class="col-sm-8"><code data-c311-status-value>{{ detail.request.status }}</code> <span data-c311-status-label>({{ statusLabel(detail.request.status) }})</span></dd>
                <dt class="col-sm-4">{{ t('field.serviceType', 'Service type') }}</dt><dd class="col-sm-8">{{ detail.request.service_type }}</dd>
                <dt class="col-sm-4">{{ t('field.department', 'Department') }}</dt><dd class="col-sm-8">{{ detail.request.owning_department }}</dd>
                <dt class="col-sm-4">{{ t('field.district', 'District') }}</dt><dd class="col-sm-8">{{ detail.request.council_district || '-' }}</dd>
                <dt class="col-sm-4">{{ t('field.origin', 'Origin') }}</dt><dd class="col-sm-8">{{ detail.request.origin_class }}</dd>
                <dt class="col-sm-4">{{ t('field.source', 'Source channel') }}</dt><dd class="col-sm-8">{{ detail.request.source_channel }}</dd>
                <dt class="col-sm-4">{{ t('field.requester', 'Requester') }}</dt><dd class="col-sm-8">{{ detail.request.primary_requester ? detail.request.primary_requester.display_name : '-' }}</dd>
                <dt class="col-sm-4">{{ t('field.location', 'Location') }}</dt><dd class="col-sm-8">{{ detail.request.location ? detail.request.location.address.line1 : '-' }}</dd>
                <dt class="col-sm-4">{{ t('field.assignee', 'Assignee') }}</dt><dd class="col-sm-8">{{ detail.primary_assignee_id || '-' }}</dd>
                <dt class="col-sm-4">{{ t('staff.assignmentNotifications', 'Assignment notifications') }}</dt><dd class="col-sm-8"><ul class="mb-0" data-c311-assignment-notifications><li v-for="notification in detail.assignment_notifications || []" :key="notification.notification_id" data-c311-assignment-notification>{{ notification.recipient_role }} · {{ notification.recipient_staff_id }} · {{ notification.result }} · {{ formatDate(notification.occurred_at) }}</li><li v-if="!detail.assignment_notifications || !detail.assignment_notifications.length">-</li></ul></dd>
                <dt id="c311-collaborators-heading" tabindex="-1" class="col-sm-4">{{ t('field.collaborators', 'Collaborators') }}</dt><dd class="col-sm-8"><ul class="mb-0" data-c311-collaborators><li v-for="collaborator in detail.collaborator_ids" :key="collaborator">{{ collaborator }} <button v-if="can('staff_collaborator_remove')" type="button" class="btn btn-link btn-sm p-0" :data-c311-action="`remove-collaborator-${collaborator}`" :disabled="actionBusy" @click="removeCollaborator(collaborator)">{{ t('action.remove', 'Remove') }}</button></li><li v-if="!detail.collaborator_ids.length">-</li></ul></dd>
                <dt class="col-sm-4">{{ t('field.duplicateGroup', 'Duplicate group') }}</dt><dd class="col-sm-8"><span data-c311-duplicate-group>{{ detail.request.duplicate_group_id || '-' }}</span></dd>
                <dt class="col-sm-4">{{ t('field.version', 'Version') }}</dt><dd class="col-sm-8"><code>{{ detail.request.version }}</code></dd>
              </dl>

              <section class="mb-3" aria-labelledby="c311-relationships-heading">
                <h3 id="c311-relationships-heading" tabindex="-1">{{ t('staff.relationships', 'Constituent relationships') }}</h3>
                <ul data-c311-relationships>
                  <li v-for="relationship in relationships" :key="`${relationship.constituent_id}-${relationship.relationship_type}`">
                    <span>{{ relationship.constituent_id }} · {{ relationship.relationship_type }} · {{ relationship.portal_visible ? t('staff.portalVisible', 'portal visible') : t('staff.internalOnly', 'internal only') }} · {{ relationship.notify_status ? t('staff.notifyStatus', 'notify status') : t('staff.noNotifyStatus', 'do not notify') }}</span>
                    <small v-if="relationship.notification_target" class="d-block" data-c311-relationship-notification-target>{{ t('staff.notificationTarget', 'Notification target') }}: {{ relationship.notification_target }}</small>
                    <small v-if="relationship.notification_result" class="d-block" data-c311-relationship-notification-result>{{ t('staff.notificationResult', 'Notification result') }}: {{ relationship.notification_result }}</small>
                    <small v-for="event in relationship.audit || []" :key="event.audit_id" class="d-block" data-c311-relationship-audit>{{ t('staff.relationshipAudit', 'Relationship audit') }}: {{ event.action }} · {{ event.actor_id }} · {{ formatDate(event.occurred_at) }}</small>
                    <button v-if="canUnlink && relationship.relationship_type !== 'PRIMARY_REQUESTER'" class="btn btn-link p-0 ml-2" type="button" :data-c311-action="`unlink-constituent-${relationship.constituent_id}`" :disabled="relationshipBusy" @click="unlinkConstituent(relationship)">{{ t('action.unlink', 'Unlink') }}</button>
                  </li>
                  <li v-if="!relationships.length">{{ t('state.empty', 'No entries') }}</li>
                </ul>
                <section v-if="relationshipAuditEvents.length" class="mt-3" data-c311-relationship-audit-events aria-labelledby="c311-relationship-audit-events-heading">
                  <h4 id="c311-relationship-audit-events-heading">{{ t('staff.relationshipAuditEvents', 'Relationship audit events') }}</h4>
                  <ol><li v-for="event in relationshipAuditEvents" :key="`${event.audit_id}-${event.action}`">{{ event.action }} · {{ event.actor_id }} · {{ formatDate(event.occurred_at) }}</li></ol>
                </section>
                <button v-if="can('staff_request_detail')" type="button" class="btn btn-outline-secondary btn-sm mb-2" data-c311-action="manage-relationships" @click="focusSection('#c311-relationships-heading')">{{ t('action.manageRelationships', 'Manage relationships') }}</button>
                <form v-if="canLink" class="border rounded p-2" data-c311-form="link-constituent" @submit.prevent="linkConstituent">
                  <label for="c311-constituent-id">{{ t('field.constituentId', 'Constituent ID') }}</label>
                  <input id="c311-constituent-id" v-model.trim="relationshipForm.constituent_id" class="form-control" required>
                  <label for="c311-relationship-type" class="mt-2">{{ t('field.relationshipType', 'Relationship type') }}</label>
                  <select id="c311-relationship-type" v-model="relationshipForm.relationship_type" class="form-control"><option v-for="type in relationshipTypes" :key="type" :value="type">{{ type }}</option></select>
                  <label class="mt-2"><input v-model="relationshipForm.portal_visible" type="checkbox"> {{ t('field.portalVisible', 'Visible in portal') }}</label>
                  <label class="ml-3"><input v-model="relationshipForm.notify_status" type="checkbox"> {{ t('field.notifyStatus', 'Notify on status changes') }}</label>
                  <button class="btn btn-primary mt-2" type="submit" data-c311-action="link-constituent" :disabled="relationshipBusy">{{ relationshipBusy ? t('action.working', 'Working...') : t('action.link', 'Link constituent') }}</button>
                </form>
                <button v-if="canUnlink && !relationships.length" type="button" class="btn btn-outline-secondary btn-sm" data-c311-action="unlink-constituent" disabled :title="t('status.noRelationshipToUnlink', 'There is no relationship to unlink.')">{{ t('action.unlinkConstituent', 'Unlink constituent') }}</button>
              </section>

              <section class="mb-3" aria-labelledby="c311-notes-heading">
                <h3 id="c311-notes-heading">{{ t('staff.notes', 'Notes') }}</h3>
                <ol data-c311-notes><li v-for="note in notes" :key="note.note_id">{{ note.body }} · {{ note.portal_visible ? t('staff.portalVisible', 'portal visible') : t('staff.internalOnly', 'internal only') }} · {{ formatDate(note.created_at) }}</li><li v-if="!notes.length">{{ t('state.empty', 'No entries') }}</li></ol>
                <form v-if="canCreateNote" class="border rounded p-2" data-c311-form="create-note" @submit.prevent="createNote">
                  <label for="c311-note-body">{{ t('field.note', 'Note') }}</label>
                  <textarea id="c311-note-body" v-model.trim="noteForm.body" class="form-control" maxlength="2000" required></textarea>
                  <label class="mt-2"><input v-model="noteForm.portal_visible" type="checkbox"> {{ t('field.portalVisible', 'Visible in portal') }}</label>
                  <button class="btn btn-primary mt-2" type="submit" data-c311-action="create-note" :disabled="noteBusy">{{ noteBusy ? t('action.working', 'Working...') : t('action.addNote', 'Add note') }}</button>
                </form>
              </section>

              <section class="mb-3" aria-labelledby="c311-history-heading"><h3 id="c311-history-heading">{{ t('staff.history', 'History') }}</h3><ul data-c311-history><li v-for="entry in detail.history" :key="`${entry.action}-${entry.occurred_at}`">{{ entry.action }} {{ formatDate(entry.occurred_at) }}</li><li v-if="!detail.history.length">{{ t('state.empty', 'No entries') }}</li></ul></section>
              <section v-if="can('audit_list')" class="mb-3" aria-labelledby="c311-audit-heading"><h3 id="c311-audit-heading">{{ t('staff.audit', 'Audit') }}</h3><ul data-c311-audit><li v-for="(entry, index) in detail.audit" :key="index">{{ entry.action || entry.event || t('state.unknown', 'Recorded event') }}</li><li v-if="!detail.audit.length">{{ t('state.empty', 'No entries') }}</li></ul></section>
              <p v-else class="small text-muted" data-c311-audit-unavailable>{{ t('status.auditUnavailable', 'Audit details require additional permission.') }}</p>
              <section class="mb-3" aria-labelledby="c311-reminders-heading"><h3 id="c311-reminders-heading">{{ t('staff.reminders', 'Reminders') }}</h3><ul data-c311-reminders><li v-for="reminder in detail.reminders" :key="reminder.reminder_id" :data-c311-reminder-id="reminder.reminder_id"><span>{{ reminder.title }} ({{ reminder.status }}) · {{ formatDate(reminder.due_at) }}</span><small class="d-block" data-c311-reminder-recipient>{{ t('field.recipient', 'Recipient') }}: {{ reminder.recipient_staff_id }}</small><small class="d-block" data-c311-reminder-channel>{{ t('field.channel', 'Channel') }}: {{ reminder.channel }}</small><span v-if="can('staff_reminder_action') && !['COMPLETED', 'CANCELLED'].includes(reminder.status)" class="d-block"><button type="button" class="btn btn-link btn-sm pl-0" :data-c311-action="`snooze-reminder-${reminder.reminder_id}`" @click="openReminderAction(reminder, 'SNOOZE')">{{ t('action.snoozeReminder', 'Snooze') }}</button><button type="button" class="btn btn-link btn-sm" :data-c311-action="`complete-reminder-${reminder.reminder_id}`" @click="actionReminder(reminder.reminder_id, 'COMPLETE')">{{ t('action.completeReminder', 'Complete') }}</button><button type="button" class="btn btn-link btn-sm" :data-c311-action="`cancel-reminder-${reminder.reminder_id}`" @click="actionReminder(reminder.reminder_id, 'CANCEL')">{{ t('action.cancelReminder', 'Cancel') }}</button></span><small v-for="(entry, index) in reminder.history || []" :key="index" class="d-block" data-c311-reminder-history>{{ entry.action }}<template v-if="entry.previous_due_at">: {{ formatDate(entry.previous_due_at) }} → {{ formatDate(entry.due_at) }}</template></small></li><li v-if="!detail.reminders.length">{{ t('state.empty', 'No reminders') }}</li></ul></section>
              <section class="mb-3" aria-labelledby="c311-attachments-heading"><h3 id="c311-attachments-heading">{{ t('staff.attachments', 'Attachments') }}</h3><ul data-c311-attachments><li v-for="attachment in attachmentEntries" :key="attachment.attachment_token || attachment.filename"><span data-c311-attachment-entry>{{ attachment.filename || t('staff.attachment', 'Attachment') }}</span> <small>{{ attachment.media_type || '' }} · {{ attachment.size || 0 }} bytes</small> <code>{{ attachment.attachment_token }}</code></li><li v-if="!attachmentEntries.length">{{ t('state.empty', 'No attachments') }}</li></ul></section>
              <section aria-labelledby="c311-external-work-order-heading" data-c311-external-work-order><h3 id="c311-external-work-order-heading">{{ t('staff.externalWorkOrder', 'External work order') }}</h3><dl v-if="detail.external_work_order" class="row"><dt class="col-sm-4">{{ t('staff.workOrderId', 'Work order ID') }}</dt><dd class="col-sm-8" data-c311-work-order-id>{{ detail.external_work_order.work_order_id }}</dd><dt class="col-sm-4">{{ t('field.requestNumber', 'Request number') }}</dt><dd class="col-sm-8" data-c311-work-order-number>{{ detail.external_work_order.service_request_number }}</dd><dt class="col-sm-4">{{ t('field.status', 'Status') }}</dt><dd class="col-sm-8" data-c311-work-order-status>{{ detail.external_work_order.status }}</dd><dt class="col-sm-4">{{ t('field.version', 'Version') }}</dt><dd class="col-sm-8">{{ detail.external_work_order.version }}</dd><dt class="col-sm-4">{{ t('field.createdAt', 'Created') }}</dt><dd class="col-sm-8">{{ formatDate(detail.external_work_order.created_at) }}</dd><dt class="col-sm-4">{{ t('field.updated', 'Updated') }}</dt><dd class="col-sm-8">{{ formatDate(detail.external_work_order.updated_at) }}</dd><dt class="col-sm-4">{{ t('staff.externalStatus', 'External status') }}</dt><dd class="col-sm-8"><a v-if="externalStatusURL" :href="externalStatusURL" target="_blank" rel="noopener noreferrer" data-c311-work-order-url>{{ t('action.viewExternalStatus', 'View external status') }}</a><span v-else>-</span></dd></dl><span v-else>-</span></section>
            </div>
            <div class="col-lg-4">
              <div class="border rounded p-3" data-c311-staff-actions>
                <h3 class="h5">{{ t('staff.actions', 'Available actions') }}</h3>
                <button v-if="canRecordAction('staff_request_transition', 'TRIAGE', ['SUBMITTED'])" type="button" class="btn btn-primary btn-sm mr-2 mb-2" data-c311-action="transition-request" data-c311-action-kind="triage" @click="triageFormOpen = !triageFormOpen">{{ t('action.triage', 'Triage') }}</button>
                <button v-if="hasAdditionalTransition" type="button" class="btn btn-outline-primary btn-sm mr-2 mb-2" data-c311-action="transition-status" @click="openTransitionForm">{{ t('action.transitionStatus', 'Transition status') }}</button>
                <button v-if="can('staff_request_detail')" type="button" class="btn btn-outline-secondary btn-sm mr-2 mb-2" data-c311-action="edit-request" disabled :title="t('status.actionNotAvailable', 'This workflow action is available in the next staff workflow stage.')">{{ t('action.edit', 'Edit request') }}</button>
                <button v-if="canRecordAction('staff_request_reassign', null, ['SUBMITTED', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS'])" type="button" class="btn btn-outline-primary btn-sm mr-2 mb-2" data-c311-action="reassign-request" @click="reassignFormOpen = !reassignFormOpen">{{ t('action.reassign', 'Reassign') }}</button>
                <button v-if="canManageCollaborators" type="button" class="btn btn-outline-secondary btn-sm mr-2 mb-2" data-c311-action="manage-collaborators" @click="collaboratorFormOpen = !collaboratorFormOpen">{{ t('action.manageCollaborators', 'Manage collaborators') }}</button>
                <button v-if="canRecordAction('staff_origin_override', null, statuses)" type="button" class="btn btn-outline-secondary btn-sm mr-2 mb-2" data-c311-action="override-origin" @click="originFormOpen = !originFormOpen">{{ t('action.overrideOrigin', 'Override origin class') }}</button>
                <button v-if="canRecordAction('staff_scope_override', null, statuses)" type="button" class="btn btn-outline-secondary btn-sm mr-2 mb-2" data-c311-action="override-scope" @click="scopeFormOpen = !scopeFormOpen">{{ t('action.overrideScope', 'Override scope') }}</button>
                <button v-if="canRecordAction('staff_duplicate_group_confirm', null, statuses) && !detail.request.duplicate_group_id" type="button" class="btn btn-outline-secondary btn-sm mr-2 mb-2" data-c311-action="confirm-duplicate" @click="duplicateFormOpen = !duplicateFormOpen">{{ t('action.confirmDuplicate', 'Confirm duplicate group') }}</button>
                <button v-if="canRecordAction('staff_duplicate_group_remove', null, statuses) && detail.request.duplicate_group_id" type="button" class="btn btn-outline-secondary btn-sm mr-2 mb-2" data-c311-action="remove-duplicate" @click="submitDuplicateRemove" :disabled="actionBusy">{{ t('action.removeDuplicate', 'Remove duplicate group') }}</button>
                <button v-if="canRecordAction('staff_reminder_create', null, ['DRAFT', 'SUBMITTED', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED'])" type="button" class="btn btn-outline-primary btn-sm mr-2 mb-2" data-c311-action="create-reminder" @click="reminderFormOpen = !reminderFormOpen">{{ t('action.createReminder', 'Create reminder') }}</button>
                <button v-if="canRecordAction('staff_reopen_approve', 'APPROVE_REOPEN', ['RESOLVED', 'CLOSED'])" type="button" class="btn btn-outline-primary btn-sm mr-2 mb-2" data-c311-action="approve-reopen" @click="approveReopen">{{ t('action.approveReopen', 'Approve reopen') }}</button>
                <form v-if="triageFormOpen" class="mt-2 border rounded p-2" data-c311-form="triage" @submit.prevent="submitTriage"><h4 class="h6">{{ t('staff.triageReview', 'Confirm triage details') }}</h4><dl><dt>{{ t('field.serviceType', 'Service type') }}</dt><dd data-c311-triage-service-type>{{ detail.request.service_type }}</dd><dt>{{ t('field.department', 'Department') }}</dt><dd data-c311-triage-department>{{ detail.request.owning_department }}</dd><dt>{{ t('field.origin', 'Origin') }}</dt><dd data-c311-triage-origin>{{ detail.request.origin_class }}</dd><dt>{{ t('field.location', 'Location') }}</dt><dd data-c311-triage-location>{{ detail.request.location ? detail.request.location.address.line1 : t('state.empty', 'No location') }}</dd><dt>{{ t('field.duplicateGroup', 'Duplicate group') }}</dt><dd data-c311-triage-duplicate>{{ detail.request.duplicate_group_id || t('filter.none', 'None') }}</dd></dl><label for="c311-triage-reason">{{ t('field.reason', 'Reason') }}</label><input id="c311-triage-reason" v-model.trim="triageForm.reason" class="form-control"><label class="mt-2"><input v-model="triageForm.confirmed" type="checkbox" data-c311-action="confirm-triage-details"> {{ t('staff.triageConfirmed', 'I reviewed the service type, department, origin, location and duplicate group.') }}</label><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-triage" :disabled="actionBusy || !triageReady">{{ t('action.confirm', 'Confirm') }}</button></form>
                <form v-if="transitionFormOpen" class="mt-2" data-c311-form="transition" @submit.prevent="submitTransition(transitionForm.to_status)"><label for="c311-transition-status">{{ t('field.status', 'Status') }}</label><select id="c311-transition-status" v-model="transitionForm.to_status" class="form-control"><option v-for="status in transitionOptions" :key="status" :value="status">{{ status }}</option></select><label for="c311-transition-reason" class="mt-2">{{ t('field.reason', 'Reason') }}</label><input id="c311-transition-reason" v-model.trim="transitionForm.reason" class="form-control"><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-transition" :disabled="actionBusy">{{ t('action.apply', 'Apply') }}</button></form>
                <form v-if="reassignFormOpen" class="mt-2" data-c311-form="reassign" @submit.prevent="submitReassign"><label for="c311-assignee">{{ t('field.assignee', 'Assignee') }}</label><input id="c311-assignee" v-model.trim="reassignForm.assignee_id" class="form-control" required><label for="c311-reassign-reason" class="mt-2">{{ t('field.reason', 'Reason') }}</label><input id="c311-reassign-reason" v-model.trim="reassignForm.reason" class="form-control" required><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-reassign" :disabled="actionBusy">{{ t('action.apply', 'Apply') }}</button></form>
                <form v-if="collaboratorFormOpen && can('staff_collaborator_add')" class="mt-2" data-c311-form="collaborator" @submit.prevent="addCollaborator"><label for="c311-collaborator-id">{{ t('field.collaborator', 'Collaborator') }}</label><input id="c311-collaborator-id" v-model.trim="collaboratorForm.staff_id" class="form-control" required><label for="c311-collaborator-reason" class="mt-2">{{ t('field.reason', 'Reason') }}</label><input id="c311-collaborator-reason" v-model.trim="collaboratorForm.reason" class="form-control" required><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="add-collaborator" :disabled="actionBusy">{{ t('action.addCollaborator', 'Add collaborator') }}</button></form>
                <form v-if="originFormOpen" class="mt-2" data-c311-form="origin" @submit.prevent="submitOrigin"><label for="c311-origin">{{ t('field.origin', 'Origin') }}</label><select id="c311-origin" v-model="originForm.origin_class" class="form-control"><option value="EXTERNAL">EXTERNAL</option><option value="INTERNAL">INTERNAL</option></select><label for="c311-origin-reason" class="mt-2">{{ t('field.reason', 'Reason') }}</label><input id="c311-origin-reason" v-model.trim="originForm.reason" class="form-control" required><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-origin" :disabled="actionBusy">{{ t('action.apply', 'Apply') }}</button></form>
                <form v-if="scopeFormOpen" class="mt-2" data-c311-form="scope" @submit.prevent="submitScope"><label for="c311-scope-department">{{ t('field.department', 'Department') }}</label><select id="c311-scope-department" v-model="scopeForm.department_code" class="form-control"><option v-for="department in departments" :key="department" :value="department">{{ department }}</option></select><label for="c311-scope-district" class="mt-2">{{ t('field.district', 'District') }}</label><select id="c311-scope-district" :value="scopeForm.district_codes[0]" @change="scopeForm.district_codes = [$event.target.value]" class="form-control"><option v-for="district in districts" :key="district" :value="district">{{ district }}</option></select><label for="c311-scope-reason" class="mt-2">{{ t('field.reason', 'Reason') }}</label><input id="c311-scope-reason" v-model.trim="scopeForm.reason" class="form-control" required><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-scope" :disabled="actionBusy">{{ t('action.apply', 'Apply') }}</button></form>
                <form v-if="duplicateFormOpen" class="mt-2" data-c311-form="duplicate" @submit.prevent="submitDuplicateConfirm"><label for="c311-duplicate-group">{{ t('field.duplicateGroup', 'Duplicate group') }}</label><input id="c311-duplicate-group" v-model.trim="duplicateForm.duplicate_group_id" class="form-control" required><label for="c311-duplicate-reason" class="mt-2">{{ t('field.reason', 'Reason') }}</label><input id="c311-duplicate-reason" v-model.trim="duplicateForm.reason" class="form-control" required><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-duplicate" :disabled="actionBusy">{{ t('action.apply', 'Apply') }}</button></form>
                <form v-if="reminderFormOpen" class="mt-2" data-c311-form="reminder" @submit.prevent="submitReminder"><label for="c311-reminder-title">{{ t('field.title', 'Title') }}</label><input id="c311-reminder-title" v-model.trim="reminderForm.title" class="form-control" required><label for="c311-reminder-due" class="mt-2">{{ t('field.dueAt', 'Due at') }}</label><input id="c311-reminder-due" v-model="reminderForm.due_at" type="datetime-local" class="form-control" required><label for="c311-reminder-recipient" class="mt-2">{{ t('field.recipient', 'Recipient') }}</label><input id="c311-reminder-recipient" v-model.trim="reminderForm.recipient_staff_id" class="form-control" required><label for="c311-reminder-channel" class="mt-2">{{ t('field.channel', 'Channel') }}</label><select id="c311-reminder-channel" v-model="reminderForm.channel" class="form-control" required><option value="IN_APP">IN_APP</option><option value="EMAIL">EMAIL</option></select><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-reminder" :disabled="actionBusy">{{ t('action.apply', 'Apply') }}</button></form>
                <form v-if="reminderActionFormOpen" class="mt-2" data-c311-form="reminder-action" @submit.prevent="submitReminderAction"><label for="c311-reminder-action-due">{{ t('field.dueAt', 'New due at') }}</label><input id="c311-reminder-action-due" v-model="reminderActionForm.due_at" type="datetime-local" class="form-control" required><button type="submit" class="btn btn-primary btn-sm mt-2" data-c311-action="submit-reminder-action" :disabled="actionBusy">{{ t('action.snoozeReminder', 'Snooze') }}</button></form>
                <button v-if="can('audit_list')" type="button" class="btn btn-outline-secondary btn-sm mr-2 mb-2" data-c311-action="view-audit" @click="markActionUnavailable('audit')">{{ t('action.viewAudit', 'View audit') }}</button>
                <p v-if="!can('audit_list')" class="small text-muted" data-c311-audit-action-unavailable>{{ t('status.auditUnavailable', 'Audit details require additional permission.') }}</p>
                <p v-if="actionMessage" class="text-info mt-2" role="status" aria-live="polite" data-c311-action-message>{{ actionMessage }}</p>
                <p v-if="actionError" class="text-danger mt-2" role="alert" data-c311-action-error>{{ actionError.message || actionError }}</p>
                <div v-if="conflictError" class="mt-2" data-c311-conflict-recovery><p data-c311-current-version>{{ t('staff.serverVersion', 'Server version') }}: {{ conflictError.currentVersion || conflictError.current_version }}</p><button type="button" class="btn btn-link btn-sm mr-2" data-c311-action="reload-current-version" @click="reloadConflictVersion">{{ t('action.reloadVersion', 'Reload current version') }}</button><button v-if="lastAction && actionConflictReloaded" type="button" class="btn btn-link btn-sm" data-c311-action="reapply-action" @click="lastAction()">{{ t('action.reapply', 'Reapply my operation') }}</button></div>
              </div>
              <p v-if="detailMessage" class="alert alert-info mt-3" role="status" data-c311-detail-message>{{ detailMessage }}</p>
            </div>
          </div>
        </section>
      </template>
    </c311-data-state>
  </c311-app-shell>
</template>

<script>
import * as C311JS from '@cortezaproject/corteza-js'
import { components, c311 } from '@cortezaproject/corteza-vue'

const { C311AppShell, C311DataState, C311HelpDrawer, C311LanguageSelector, C311MainNav, C311ResponsiveData } = components
const c311StateForError = c311?.c311StateForError
const formatDate = value => {
  try { return typeof C311JS.formatC311DateTime === 'function' ? C311JS.formatC311DateTime(value) : value || '' } catch (_error) { return value || '' }
}

export default {
  name: 'C311Staff',
  components: { C311AppShell, C311DataState, C311HelpDrawer, C311LanguageSelector, C311MainNav, C311ResponsiveData },
  data: () => ({
    state: 'loading', dataError: null, statusMessage: '', actionError: null, actionMessage: '', detailMessage: '', detail: null, selectedRequest: null, items: [],
    page: { items: [], next_page_token: null, total_count: 0 }, pageTokenHistory: [],
    filters: { status: '', service_type: '', department: '', district: '', origin_class: '', source_channel: '', assignee: '', collaborator: '', category: '', created_from: '', created_to: '', duplicate_group: '' },
    sort: '', pageSize: 50, requestGeneration: 0,
    relationships: [], audit: [], notes: [], relationshipBusy: false, noteBusy: false,
    selectedRequestIds: [], bulkConfirmOpen: false, bulkBusy: false, bulkError: null, bulkMessage: '', bulkIdempotencyKey: '', bulkConflictReloaded: false,
    bulkForm: { action: 'UPDATE', primary_assignee_id: '', status: '', priority: '', staff_note: '' },
    actionBusy: false, triageFormOpen: false, transitionFormOpen: false, reassignFormOpen: false, collaboratorFormOpen: false, originFormOpen: false, scopeFormOpen: false, duplicateFormOpen: false, reminderFormOpen: false, reminderActionFormOpen: false,
    transitionForm: { to_status: 'TRIAGED', reason: '' }, reassignForm: { assignee_id: '', reason: '' }, originForm: { origin_class: 'EXTERNAL', reason: '' },
    scopeForm: { department_code: 'STREETS', district_codes: ['NORTH'], reason: '' }, duplicateForm: { duplicate_group_id: '', reason: '' },
    triageForm: { confirmed: false, reason: '' }, collaboratorForm: { staff_id: '', reason: '' }, reminderForm: { title: '', due_at: '', timezone: 'America/New_York', recipient_staff_id: '', channel: 'IN_APP' }, reminderActionForm: { reminder_id: '', due_at: '' }, lastAction: null, conflictError: null, actionConflictReloaded: false,
    relationshipForm: { constituent_id: '', relationship_type: 'AFFECTED_RESIDENT', portal_visible: true, notify_status: false },
    noteForm: { body: '', portal_visible: false }, relationshipTypes: ['PRIMARY_REQUESTER', 'AFFECTED_RESIDENT', 'PROPERTY_OWNER', 'REPORTER', 'ORGANISATION_CONTACT'],
    statuses: ['DRAFT', 'SUBMITTED', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REOPENED'], serviceTypes: ['TREE_MAINTENANCE', 'POTHOLE', 'MISSED_TRASH', 'GENERAL_INQUIRY'], departments: ['PUBLIC_WORKS', 'STREETS', 'SANITATION', 'GENERAL_SERVICES'], districts: ['NORTH', 'CENTRAL', 'SOUTH'],
    columns: [
      { key: 'request_number', labelKey: 'field.requestNumber' }, { key: 'summary', labelKey: 'field.summary' }, { key: 'status', labelKey: 'field.status' }, { key: 'owning_department', labelKey: 'field.department' }, { key: 'updated_at', labelKey: 'field.updated', format: value => formatDate(value) },
      { key: 'service_type', labelKey: 'field.serviceType' }, { key: 'origin_class', labelKey: 'field.origin' }, { key: 'source_channel', labelKey: 'field.source' }, { key: 'council_district', labelKey: 'field.district' }, { key: 'primary_assignee_id', labelKey: 'field.assignee' }, { key: 'duplicate_group_id', labelKey: 'field.duplicateGroup' }, { key: 'version', labelKey: 'field.version' },
    ],
  }),
  computed: {
    actor () { return this.$C311?.session?.actor || null }, actorID () { return this.actor?.actor_id || '' },
    isDetailRoute () { return !!this.$route?.params?.request_id },
    isDetailView () { return this.isDetailRoute || !!this.detail },
    navItems () { return [{ route: '/c311/staff', label: this.t('navigation.requests', 'Requests'), capability: 'staff_request_queue' }, { route: '/c311/staff/reports', label: this.t('navigation.reports', 'Reports'), capability: 'report_catalogue' }, { route: '/c311/staff/workflows', label: this.t('navigation.workflows', 'Workflows'), capability: 'workflow_list', scope: 'workflow.execute' }] },
    translatedColumns () { return this.columns.map(column => ({ ...column, label: this.t(column.labelKey, column.labelKey), ...(column.key === 'status' ? { format: value => `${value} (${this.statusLabel(value)})` } : {}) })) },
    requestQuery () { return { ...Object.fromEntries(Object.entries(this.filters).filter(([, value]) => value !== '')), page_size: this.pageSize, ...(this.sort ? { sort: this.sort } : {}) } },
    canCapability () { return capability => typeof this.$C311?.can === 'function' ? this.$C311.can(capability) : !!this.actor?.capabilities?.includes(capability) },
    canLink () { return this.canRecordAction('staff_constituent_link') }, canUnlink () { return this.canRecordAction('staff_constituent_unlink') }, canCreateNote () { return this.canRecordAction('staff_note_create') },
    canManageCollaborators () { return !!this.detail?.request?.status && this.statuses.includes(this.detail.request.status) && (this.can('staff_collaborator_add') || this.can('staff_collaborator_remove')) },
    transitionOptions () { return this.statuses.filter(status => status !== 'TRIAGED' && this.transitionTargetsForCurrent(status)) },
    hasAdditionalTransition () { return this.can('staff_request_transition') && this.transitionOptions.length > 0 },
    triageReady () { return !!this.triageForm.confirmed && !!this.detail?.request?.service_type && !!this.detail?.request?.owning_department && !!this.detail?.request?.origin_class && (this.detail.request.service_type === 'GENERAL_INQUIRY' || !!this.detail.request.location) },
    selectedItems () { const selected = new Set(this.selectedRequestIds); return this.items.filter(item => selected.has(item.request_id)) },
    bulkChanges () { const changes = Object.fromEntries(Object.entries(this.bulkForm).filter(([key, value]) => key !== 'action' && value !== '' && !(key === 'status' && this.bulkForm.action === 'CLOSE'))); return changes },
    bulkChangeSummary () { const changes = Object.entries(this.bulkChanges).map(([key, value]) => `${key}: ${value}`); return changes.join(', ') || this.t('staff.noFieldChanges', 'No field changes') },
    relationshipAuditEvents () { return this.audit.filter(event => ['LINKED', 'UNLINKED', 'UPDATED'].includes(event.action)) },
    attachmentEntries () {
      if (this.detail?.attachments?.length) return this.detail.attachments
      return (this.detail?.request?.custom_fields?.attachment_tokens || []).map(attachmentToken => ({ attachment_token: attachmentToken }))
    },
    externalStatusURL () { const value = this.detail?.external_work_order?.external_status_url; return typeof value === 'string' && /^https?:\/\//i.test(value) ? value : '' },
  },
  watch: { '$route.params.request_id': 'loadFromRoute' },
  created () { this.restoreQueueState(); this.loadFromRoute() },
  methods: {
    t (key, fallback) { const translated = this.$t?.(`c311:${key}`); return translated && translated !== `c311:${key}` && translated !== key ? translated : fallback },
    formatDate, statusLabel (status) { return this.t(`status.value.${String(status).toLowerCase()}`, status) }, can (capability) { return this.canCapability(capability) },
    hasAvailableAction (action) { return !!this.detail?.available_actions?.includes(action) },
    canRecordAction (capability, action = null, statuses = []) {
      if (!this.detail || !this.can(capability)) return false
      if (action && !this.hasAvailableAction(action)) return false
      return !statuses.length || statuses.includes(this.detail.request.status)
    },
    focusSection (selector) { this.$nextTick(() => this.$el.querySelector(selector)?.focus()) },
    markActionUnavailable () { this.actionError = null; this.actionMessage = this.t('status.actionNotAvailable', 'This workflow action is available in the next staff workflow stage.') },
    normalizeDetail (response) { return { ...response, available_actions: response?.available_actions || [], collaborator_ids: response?.collaborator_ids || [], reminders: response?.reminders || [], attachments: response?.attachments || [], history: response?.history || [], audit: response?.audit || [], relationships: response?.relationships || [], notes: response?.notes || [], assignment_notifications: response?.assignment_notifications || [] } },
    applyFilters () { this.pageTokenHistory = []; this.load() },
    async loadFromRoute () { this.detail = null; this.selectedRequest = null; this.relationships = []; this.notes = []; this.audit = []; this.detailMessage = ''; this.conflictError = null; this.actionConflictReloaded = false; return this.isDetailRoute ? this.loadDetail(this.$route.params.request_id) : this.load() },
    retryCurrentView () { return this.isDetailRoute ? this.loadDetail(this.$route.params.request_id) : this.load() },
    restoreQueueState () { try { const raw = sessionStorage.getItem('c311.staff.queue'); if (raw) { const saved = JSON.parse(raw); this.filters = { ...this.filters, ...(saved.filters || {}) }; this.sort = saved.sort || ''; this.pageSize = saved.pageSize || 50; this.pageTokenHistory = saved.pageTokenHistory || [] } } catch (_error) {} },
    persistQueueState () { try { sessionStorage.setItem('c311.staff.queue', JSON.stringify({ filters: this.filters, sort: this.sort, pageSize: this.pageSize, pageTokenHistory: this.pageTokenHistory })) } catch (_error) {} },
    async load () {
      const generation = ++this.requestGeneration; this.persistQueueState(); this.state = 'loading'; this.dataError = null; this.statusMessage = this.t('status.loadingRequests', 'Loading requests.'); this.detail = null
      try { const page = await this.$C311?.provider?.listStaffRequests?.({ ...this.requestQuery, ...(this.pageTokenHistory.length ? { page_token: this.pageTokenHistory[this.pageTokenHistory.length - 1] } : {}) }); if (generation !== this.requestGeneration || this.isDetailRoute) return; this.page = page || { items: [], next_page_token: null, total_count: 0 }; this.items = this.page.items || []; this.selectedRequestIds = this.selectedItems.map(item => item.request_id); if (!this.selectedRequestIds.length) this.bulkConfirmOpen = false; this.state = this.items.length ? 'populated' : 'empty'; this.statusMessage = this.items.length ? this.t('status.requestsLoaded', 'Requests loaded.') : this.t('status.noRequests', 'No requests found.') } catch (error) { if (generation !== this.requestGeneration || this.isDetailRoute) return; this.dataError = error; this.state = c311StateForError?.(error) || (error?.retryable ? 'retryable-error' : 'terminal-error'); this.statusMessage = this.t('status.requestListUnavailable', 'Request list unavailable.') }
    },
    async loadDetail (requestID = this.$route?.params?.request_id) {
      if (!requestID) return this.load(); const generation = ++this.requestGeneration; this.state = 'loading'; this.dataError = null; this.statusMessage = this.t('status.loadingRequest', 'Loading request.')
      try { const response = await this.$C311?.provider?.getStaffRequest?.(requestID); if (generation !== this.requestGeneration) return; const detail = this.normalizeDetail(response); this.detail = detail; this.selectedRequest = detail.request || null; this.relationships = detail.relationships; this.notes = detail.notes; this.audit = detail.audit; this.state = 'populated'; this.statusMessage = this.t('status.requestLoaded', 'Request loaded.'); this.$nextTick(() => this.$el.querySelector('[data-c311-request-detail] h2')?.focus()) } catch (error) { if (generation !== this.requestGeneration) return; this.detail = null; this.dataError = error; this.state = c311StateForError?.(error) || (error?.retryable ? 'retryable-error' : 'terminal-error'); this.statusMessage = this.t('status.requestUnavailable', 'Request unavailable.') }
    },
    async selectRequest (item) { if (!item) return; if (this.$router?.push && Array.isArray(this.$route?.matched)) return this.$router.push({ name: 'c311.staff.detail', params: { request_id: item.request_id } }); return this.loadDetail(item.request_id) },
    backToQueue () { if (this.$router?.push) this.$router.push({ name: 'c311.staff' }); else { this.$route.params.request_id = undefined; this.loadFromRoute() } },
    nextPage () { if (this.page.next_page_token) { this.pageTokenHistory.push(this.page.next_page_token); this.load() } }, previousPage () { if (this.pageTokenHistory.length) { this.pageTokenHistory.pop(); this.load() } },
    async linkConstituent () { if (!this.canLink || this.relationshipBusy || !this.detail) return; this.relationshipBusy = true; this.detailMessage = ''; try { const result = this.normalizeDetail(await this.$C311.provider.linkStaffConstituent(this.detail.request.request_id, { ...this.relationshipForm }, { expectedVersion: this.detail.request.version })); this.detail = result; this.selectedRequest = result.request; this.relationships = result.relationships; this.audit = result.audit; this.detailMessage = this.t('status.relationshipLinked', 'Constituent relationship linked.'); this.relationshipForm.constituent_id = '' } catch (error) { this.actionError = error; this.detailMessage = ''; this.statusMessage = this.t('status.actionUnavailable', 'Action unavailable.') } finally { this.relationshipBusy = false } },
    async unlinkConstituent (relationship) { if (!this.canUnlink || this.relationshipBusy || !this.detail) return; this.relationshipBusy = true; this.detailMessage = ''; try { const result = this.normalizeDetail(await this.$C311.provider.unlinkStaffConstituent(this.detail.request.request_id, relationship.constituent_id, { reason: this.t('status.relationshipUnlinkReason', 'Removed by staff.') }, { expectedVersion: this.detail.request.version })); this.detail = result; this.selectedRequest = result.request; this.relationships = result.relationships; this.audit = result.audit; this.detailMessage = this.t('status.relationshipUnlinked', 'Constituent relationship removed.') } catch (error) { this.actionError = error; this.detailMessage = ''; this.statusMessage = this.t('status.actionUnavailable', 'Action unavailable.') } finally { this.relationshipBusy = false } },
    async createNote () { if (!this.canCreateNote || this.noteBusy || !this.detail) return; this.noteBusy = true; this.detailMessage = ''; try { const note = await this.$C311.provider.createStaffNote(this.detail.request.request_id, { ...this.noteForm }); this.notes = this.notes.concat(note); this.noteForm.body = ''; this.detailMessage = this.t('status.noteAdded', 'Note added.') } catch (error) { this.actionError = error; this.detailMessage = ''; this.statusMessage = this.t('status.actionUnavailable', 'Action unavailable.') } finally { this.noteBusy = false } },
    applyActionResult (response, message) { const result = this.normalizeDetail(response); this.detail = result; this.selectedRequest = result.request; this.relationships = result.relationships; this.notes = result.notes; this.audit = result.audit; this.actionError = null; this.conflictError = null; this.actionConflictReloaded = false; this.actionMessage = message },
    async runMutation (operation, message) {
      if (!this.detail || this.actionBusy) return
      this.actionBusy = true; this.actionError = null; this.conflictError = null
      try { const result = await operation(this.detail.request.version); this.applyActionResult(result, message) } catch (error) { this.actionError = error; this.conflictError = error?.status === 409 ? error : null; this.actionConflictReloaded = false; this.actionMessage = '' } finally { this.actionBusy = false }
    },
    async submitTriage () { if (!this.triageReady) return; await this.submitTransition('TRIAGED', this.triageForm.reason); if (!this.actionError) this.triageFormOpen = false },
    openTransitionForm () { this.transitionFormOpen = !this.transitionFormOpen; if (this.transitionFormOpen && this.transitionOptions.length) this.transitionForm.to_status = this.transitionOptions[0] },
    submitTransition (toStatus, reason = this.transitionForm.reason) {
      if (!this.detail || !this.canRecordAction('staff_request_transition') || !this.transitionTargetsForCurrent(toStatus)) return
      this.lastAction = () => this.submitTransition(toStatus, reason)
      return this.runMutation(version => this.$C311.provider.transitionStaffRequest(this.detail.request.request_id, { to_status: toStatus, ...(reason ? { reason } : {}) }, { expectedVersion: version }), this.t('status.transitionApplied', 'Status transition applied.'))
    },
    transitionTargetsForCurrent (toStatus) { const map = { SUBMITTED: ['TRIAGED'], TRIAGED: ['ASSIGNED'], ASSIGNED: ['IN_PROGRESS'], IN_PROGRESS: ['RESOLVED'], RESOLVED: ['CLOSED', 'REOPENED'], CLOSED: ['REOPENED'], REOPENED: ['ASSIGNED', 'IN_PROGRESS'] }; return !!map[this.detail?.request?.status]?.includes(toStatus) && this.hasAvailableAction(toStatus === 'TRIAGED' ? 'TRIAGE' : toStatus === 'ASSIGNED' ? 'ASSIGN' : toStatus === 'IN_PROGRESS' ? 'START_PROGRESS' : toStatus === 'RESOLVED' ? 'RESOLVE' : toStatus === 'CLOSED' ? 'CLOSE' : 'REQUEST_REOPEN') },
    submitReassign () { if (!this.detail || !this.reassignForm.assignee_id) return; this.lastAction = () => this.submitReassign(); return this.runMutation(version => this.$C311.provider.reassignStaffRequest(this.detail.request.request_id, { ...this.reassignForm }, { expectedVersion: version }), this.t('status.reassigned', 'Request reassigned.')) },
    addCollaborator () { if (!this.detail || !this.collaboratorForm.staff_id || !this.can('staff_collaborator_add')) return; const input = { reason: this.collaboratorForm.reason }; const staffID = this.collaboratorForm.staff_id; this.lastAction = () => this.addCollaborator(); return this.runMutation(version => this.$C311.provider.addStaffCollaborator(this.detail.request.request_id, staffID, input, { expectedVersion: version }), this.t('status.collaboratorAdded', 'Collaborator added.')) },
    removeCollaborator (staffID) { if (!this.detail || !this.can('staff_collaborator_remove')) return; const input = { reason: this.collaboratorForm.reason || this.t('status.collaboratorRemovedReason', 'Removed by staff.') }; this.lastAction = () => this.removeCollaborator(staffID); return this.runMutation(version => this.$C311.provider.removeStaffCollaborator(this.detail.request.request_id, staffID, input, { expectedVersion: version }), this.t('status.collaboratorRemoved', 'Collaborator removed.')) },
    submitOrigin () { if (!this.detail) return; this.lastAction = () => this.submitOrigin(); return this.runMutation(version => this.$C311.provider.overrideStaffOrigin(this.detail.request.request_id, { ...this.originForm }, { expectedVersion: version }), this.t('status.originUpdated', 'Origin class updated.')) },
    submitScope () { if (!this.detail || !this.canRecordAction('staff_scope_override', null, this.statuses)) return; this.lastAction = () => this.submitScope(); return this.runMutation(version => this.$C311.provider.overrideStaffScope(this.detail.request.request_id, { ...this.scopeForm, district_codes: [...this.scopeForm.district_codes] }, { expectedVersion: version }), this.t('status.scopeUpdated', 'Scope updated.')) },
    submitDuplicateConfirm () { if (!this.detail || !this.canRecordAction('staff_duplicate_group_confirm', null, this.statuses)) return; this.lastAction = () => this.submitDuplicateConfirm(); return this.runMutation(version => this.$C311.provider.confirmStaffDuplicateGroup(this.detail.request.request_id, { ...this.duplicateForm }, { expectedVersion: version }), this.t('status.duplicateConfirmed', 'Duplicate group confirmed.')) },
    submitDuplicateRemove () { if (!this.detail || !this.detail.request.duplicate_group_id || !this.canRecordAction('staff_duplicate_group_remove', null, this.statuses)) return; this.lastAction = () => this.submitDuplicateRemove(); return this.runMutation(version => this.$C311.provider.removeStaffDuplicateGroup(this.detail.request.request_id, { reason: this.duplicateForm.reason || this.t('status.duplicateRemovedReason', 'Removed by staff.') }, { expectedVersion: version }), this.t('status.duplicateRemoved', 'Duplicate group removed.')) },
    submitReminder () { if (!this.detail) return; const input = { ...this.reminderForm, due_at: new Date(this.reminderForm.due_at).toISOString() }; this.actionBusy = true; this.actionError = null; this.$C311.provider.createStaffReminder(this.detail.request.request_id, input).then(reminder => { this.detail.reminders.push(reminder); this.reminderFormOpen = false; this.actionMessage = this.t('status.reminderCreated', 'Reminder created.') }).catch(error => { this.actionError = error }).finally(() => { this.actionBusy = false }) },
    openReminderAction (reminder) { this.reminderActionForm = { reminder_id: reminder.reminder_id, due_at: '' }; this.reminderActionFormOpen = true },
    submitReminderAction () { if (!this.reminderActionForm.reminder_id || !this.reminderActionForm.due_at) return; return this.actionReminder(this.reminderActionForm.reminder_id, 'SNOOZE', { due_at: new Date(this.reminderActionForm.due_at).toISOString() }) },
    actionReminder (reminderID, action, input = {}) { if (!this.detail) return; this.actionBusy = true; this.actionError = null; return this.$C311.provider.actionStaffReminder(reminderID, action, input).then(reminder => { const index = this.detail.reminders.findIndex(item => item.reminder_id === reminderID); if (index >= 0) this.$set(this.detail.reminders, index, reminder); this.reminderActionFormOpen = false; this.actionMessage = this.t('status.reminderUpdated', 'Reminder updated.'); return reminder }).catch(error => { this.actionError = error }).finally(() => { this.actionBusy = false }) },
    approveReopen () { if (!this.detail) return; this.lastAction = () => this.approveReopen(); return this.runMutation(version => this.$C311.provider.approveStaffReopen(this.detail.request.request_id, { reason: this.t('status.reopenReason', 'Approved by staff.') }, { expectedVersion: version }), this.t('status.reopenApproved', 'Reopen approved.')) },
    async reloadConflictVersion () { await this.loadDetail(); if (this.detail) this.actionConflictReloaded = true },
    openBulkConfirmation () { if (this.selectedItems.length) { this.selectedRequestIds = this.selectedItems.map(item => item.request_id); this.bulkIdempotencyKey = `bulk-${Date.now()}`; this.bulkConflictReloaded = false; this.bulkConfirmOpen = true } },
    async submitBulk () {
      if (!this.selectedItems.length || this.bulkBusy) return
      const request_items = this.selectedItems.map(item => ({ request_id: item.request_id, expected_version: item.version }))
      const changes = this.bulkChanges
      this.bulkBusy = true; this.bulkError = null; this.bulkMessage = ''
      try { const result = await this.$C311.provider.bulkStaffRequests({ action: this.bulkForm.action, changes, request_items }, { idempotencyKey: this.bulkIdempotencyKey || `bulk-${Date.now()}` }); this.bulkMessage = `${result.updated_count} ${this.t('staff.updated', 'requests updated.')}`; this.selectedRequestIds = []; this.bulkConfirmOpen = false; this.bulkConflictReloaded = false; await this.load() } catch (error) { this.bulkError = error; this.bulkConflictReloaded = false } finally { this.bulkBusy = false }
    },
    async reloadBulkConflict () { const selected = [...this.selectedRequestIds]; await this.load(); this.selectedRequestIds = selected.filter(id => this.items.some(item => item.request_id === id)); this.bulkConflictReloaded = true },
    reapplyBulk () { if (this.bulkConflictReloaded) return this.submitBulk() },
  },
}
</script>
